### ISSUE TITLE
Evaluation过程中遇到问题

### ISSUE THREAD

**Issue by spiceandwolf** [StCarmen/PRICE#1]
执行evaluate.py至stats的workload时遇到问题
File "/perror_input.py", line 21, in generate_perror_input
    assert len(tags) == len(model_pred_cards), f"len(tags): {len(tags)}, len(model_pred_cards): {len(model_pred_cards)}"
AssertionError: len(tags): 2749, len(model_pred_cards): 2748
将generate_perror_input()注释后不影响后续执行

**Comment by StCarmen** [comment]
从报错来看是query的数量对不上，请比对一下PRICE/datas/workloads/test/stats/workloads.sql

**Comment by StCarmen** [comment]
从报错来看是query的数量对不上，请比对以下两个文件是否和仓库中的一致：
1. PRICE/datas/workloads/test/stats/workloads.sql
2. PRICE/datas/workloads/test/stats/workloads_all.sql

generate_perror_input()是为了进行p-error和e2e时间评测所准备的文件，所以如果没有p-error计算的需求可以将其注释。
